version: "3"
services:
  host:
    container_name: realstate-host
    networks:
      - realstate-network
    image: nginx:alpine
    volumes:
      - ../public:/var/www/public
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "database"
    depends_on:
      - "database"
    ports:
      - "8085:80"

  app:
    user: ${UID}:${GID}
    container_name: realstate-app
    build:
      context: ../
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ../:/var/www
      - /var/www/vendor/
    working_dir: /var/www
    networks:
      - realstate-network
    links:
      - "database"
    depends_on:
      - "database"
  
  database:
    container_name: realstate-database
    networks:
      - realstate-network
    image: mysql:8
    volumes:
      - realstatedb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "33008:3306"
    
volumes:
  realstatedb:

networks:
  realstate-network: